language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install

env:
  global:
    - ENCRYPTION_LABEL: "14e7f88b793c"

install:
  sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
  sudo apt-get update -qq &&
  sudo apt-get -qq -f install &&
  sudo apt-get install -qq emacs-snapshot;

script:
  bash ./travis-build.sh
